Repository boostcampwm-2024/web21-TICLE, pull requests merged in 2024-11, with the labels that each got.

#97 [Feat] React + Vite + Typescript 초기 설정
  apps/client/.eslintrc.js
  apps/client/package.json
  apps/client/src/index.ts
  apps/client/tsconfig.json
  apps/web/.eslintrc.cjs
  apps/web/.gitignore
  apps/web/README.md
  apps/web/index.html
  apps/web/package.json
  apps/web/src/App.tsx
  apps/web/src/main.tsx
  apps/web/src/vite-env.d.ts
  apps/web/tsconfig.app.json
  apps/web/tsconfig.json
  apps/web/tsconfig.node.json
  apps/web/vite.config.ts
  packages/eslint/paths.js
  pnpm-lock.yaml
Labels: FE, 🔨 Config, size/xl

#98 [Feat] Nestjs 초기 설정
  apps/api/.eslintrc.cjs
  apps/api/.gitignore
  apps/api/README.md
  apps/api/nest-cli.json
  apps/api/package.json
  apps/api/src/app.controller.spec.ts
  apps/api/src/app.controller.ts
  apps/api/src/app.module.ts
  apps/api/src/app.service.ts
  apps/api/src/main.ts
  apps/api/test/app.e2e-spec.ts
  apps/api/test/jest-e2e.json
  apps/api/tsconfig.build.json
  apps/api/tsconfig.json
  apps/server/.eslintrc.js
  apps/server/package.json
  apps/server/src/index.ts
  apps/server/tsconfig.json
  packages/tsconfig/nestjs.json
  pnpm-lock.yaml
Labels: BE, 🔨 Config, size/xl

#100 [Chore] size comment 제거
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/labeler.yml
Labels: 🔨 Config, size/xs

#101 [Feat] api endpoint 목록 작성
  apps/api/src/app.module.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/main.ts
  apps/api/src/stream/stream.controller.ts
  apps/api/src/stream/stream.module.ts
  apps/api/src/ticle/ticle.controller.ts
  apps/api/src/ticle/ticle.module.ts
  apps/api/src/user/user.controller.ts
  apps/api/src/user/user.module.ts
Labels: BE, ✨ Feature, size/s

#102 [Feat] swagger 세팅
  apps/api/package.json
  apps/api/src/app.controller.ts
  apps/api/src/main.ts
  pnpm-lock.yaml
Labels: BE, 🔨 Config, size/m

#103 [Feat] Tailwind 초기 세팅 및 theme 세팅
  apps/web/.eslintrc.cjs
  apps/web/index.html
  apps/web/package.json
  apps/web/postcss.config.js
  apps/web/src/main.tsx
  apps/web/src/styles/global.css
  apps/web/tailwind.config.ts
  pnpm-lock.yaml
Labels: FE, 🔨 Config, size/m

#104 [Feat] TypeORM 세팅
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/config/dbConfig.ts
  apps/api/src/main.ts
  pnpm-lock.yaml
Labels: BE, 🔨 Config, size/m

#107 [Fix] postcss.config를 es module 문법으로 변경
  apps/web/postcss.config.js
Labels: 🛠️ Fix, FE, size/xs

#109 [Feat] TypeORM Entity 생성
  apps/api/src/ entity/applicant.entity.ts
  apps/api/src/ entity/summary.entity.ts
  apps/api/src/ entity/tag.entity.ts
  apps/api/src/ entity/ticle.entity.ts
  apps/api/src/ entity/user.entity.ts
Labels: BE, ✨ Feature, size/m

#110 [Feat] Type ORM 환경변수 세팅
  apps/api/config/typeorm.config.ts
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/config/dbConfig.ts
  pnpm-lock.yaml
Labels: BE, 🔨 Config, size/m

#115 [Docs] README 수정
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 📝 Docs, size/s

#112 [Feat] TypeORM repository 연결 및 설정 변경
  apps/api/config/typeorm.config.ts
  apps/api/src/entity/applicant.entity.ts
  apps/api/src/entity/summary.entity.ts
  apps/api/src/entity/tag.entity.ts
  apps/api/src/entity/ticle.entity.ts
  apps/api/src/entity/user.entity.ts
  apps/api/src/ticle/ticle.module.ts
  apps/api/src/user/user.module.ts
Labels: BE, 🔨 Config, size/s

#117 [Feat] 프론트엔드 eslint, prettier 세팅
  .gitmessage
  apps/web/.eslintrc.cjs
  apps/web/.prettierrc.cjs
  apps/web/package.json
  apps/web/postcss.config.cjs
  packages/eslint/index.js
  pnpm-lock.yaml
Labels: FE, 🔨 Config, size/m

#113 [Feat] Tanstack Router 라우팅 세팅
  apps/web/package.json
  apps/web/src/App.tsx
  apps/web/src/components/common/Header.tsx
  apps/web/src/components/dashboard/index.tsx
  apps/web/src/routeTree.gen.ts
  apps/web/src/routes/__root.tsx
  apps/web/src/routes/auth/login.tsx
  apps/web/src/routes/auth/oauth.tsx
  apps/web/src/routes/dashboard/_layout.tsx
  apps/web/src/routes/dashboard/apply.tsx
  apps/web/src/routes/dashboard/open.tsx
  apps/web/src/routes/index.tsx
  apps/web/src/routes/live/$ticleId.tsx
  apps/web/src/routes/ticle/$ticleId.tsx
  apps/web/src/routes/ticle/open.tsx
  apps/web/tailwind.config.ts
  apps/web/vite.config.ts
Labels: FE, 🔨 Config, ✨ Feature, size/l

#120 [Feat] PR lint, tsc, prettier 검사 workflow 구현
  .github/workflows/check.yml
  .github/workflows/labeler.yml
  apps/api/package.json
  apps/web/package.json
  apps/web/src/App.tsx
  apps/web/src/components/common/Header.tsx
  apps/web/src/components/dashboard/index.tsx
  apps/web/src/routes/index.tsx
  package.json
  packages/eslint/index.js
  packages/eslint/paths.js
  packages/shared/.eslintrc.js
  packages/shared/index.ts
  packages/shared/package.json
  packages/shared/tsconfig.json
  pnpm-lock.yaml
  turbo.json
Labels: 🔨 Config, size/l

#124 [Feat] cn util 구현
  apps/web/package.json
  apps/web/src/utils/cn.ts
  pnpm-lock.yaml
Labels: FE, 🔨 Config, size/l

#118 [Feat] passport 모듈 기초세팅
  apps/api/package.json
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/strategy/github.strategy.ts
  apps/api/src/auth/strategy/google.strategy.ts
  apps/api/src/auth/strategy/local.strategy.ts
  apps/api/src/user/user.module.ts
  apps/api/src/user/user.service.ts
  pnpm-lock.yaml
Labels: BE, 🔨 Config

#129 [Feat] Dashboard api endpoint 작성
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/dashboard/dashboard.controller.ts
  apps/api/src/dashboard/dashboard.module.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/s

#127 [Feat] local login 전략 생성
  apps/api/package.json
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/strategy/local.strategy.spec.ts
  apps/api/src/auth/strategy/local.strategy.ts
  apps/api/src/entity/applicant.entity.ts
  apps/api/src/ticle/ticle.module.ts
  apps/api/src/user/dto/create-user.dto.ts
  apps/api/src/user/user.module.ts
  apps/api/src/user/user.service.spec.ts
  apps/api/src/user/user.service.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/m

#133 [Feat] 티클 생성 API 구현
  apps/api/src/ticle/dto/createTicleDto.ts
  apps/api/src/ticle/ticle.controller.ts
  apps/api/src/ticle/ticle.module.ts
  apps/api/src/ticle/ticle.service.ts
Labels: BE, ✨ Feature, size/s

#141 [Feat] Dialog 공통 컴포넌트 구현
  apps/web/package.json
  apps/web/src/assets/icons/close.svg
  apps/web/src/components/common/Dialog/index.tsx
  apps/web/src/components/common/Portal/index.tsx
  apps/web/src/hooks/useModal.ts
  apps/web/src/hooks/useOutsideClick.ts
  pnpm-lock.yaml
Labels: FE, ✨ Feature, size/m

#135 [Chore] Turborepo build 설정 및 Docker를 통한 CD 파이프 라인 구축
  .github/workflows/back-api-cd.yml
  .github/workflows/front-web-cd.yml
  .husky/pre-commit
  apps/api/Dockerfile
  apps/api/turbo.json
  apps/web/Dockerfile
  apps/web/turbo.json
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: 🔨 Config, ✨ Feature, size/l

#140 [Feat] local login api 생성
  apps/api/package.json
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.spec.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/dto/localLoginRequest.dto.ts
  apps/api/src/auth/dto/localLoginResponse.dto.ts
  apps/api/src/auth/dto/signupRequest.dto.ts
  apps/api/src/auth/dto/signupResponse.dto.ts
  apps/api/src/auth/jwt/jwt.strategy.ts
  apps/api/src/auth/local/local-auth.guard.ts
  apps/api/src/auth/local/local.strategy.spec.ts
  apps/api/src/auth/local/local.strategy.ts
  apps/api/src/auth/strategy/github.strategy.ts
  apps/api/src/auth/strategy/google.strategy.ts
  apps/api/src/auth/strategy/local.strategy.spec.ts
  apps/api/src/entity/ticle.entity.ts
  apps/api/src/entity/user.entity.ts
  apps/api/src/user/dto/create-user.dto.ts
  apps/api/src/user/user.service.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/l

#153 [Feat] 신청한 티클 가져오기 API 구현
  apps/api/src/dashboard/dashboard.controller.ts
  apps/api/src/dashboard/dashboard.module.ts
  apps/api/src/dashboard/dashboard.service.ts
Labels: BE, ✨ Feature, size/s

#148 [Feat] Button Component 구현
  .vscode/settings.json
  apps/web/.prettierrc.cjs
  apps/web/src/components/common/Button/index.tsx
  apps/web/src/components/common/TextArea/index.tsx
Labels: FE, ✨ Feature, size/m

#150 [Feat] Badge Component 구현
  apps/web/src/components/common/Badge/index.tsx
Labels: FE, ✨ Feature, size/s

#138 [Feat] SearchInput 공통 컴포넌트 구현
  apps/web/src/assets/icons/search.svg
  apps/web/src/components/common/SearchInput/index.tsx
  apps/web/src/components/common/TextArea/index.tsx
  apps/web/src/components/common/TextInput/index.tsx
  apps/web/src/constants/variants.ts
  apps/web/src/routes/index.tsx
  apps/web/src/styles/global.css
  apps/web/src/utils/getDescribedByIds.ts
Labels: FE, ✨ Feature, size/s

#159 [Feat] Avatar Component 구현
  apps/web/src/assets/icons/person.svg
  apps/web/src/components/common/Avatar/index.tsx
  apps/web/tailwind.config.ts
Labels: FE, ✨ Feature, size/s

#164 [Feat] : JWT AuthGuard생성 및 모듈에러 수정
  apps/api/package.json
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.spec.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/jwt/jwt-auth.guard.ts
  apps/api/src/auth/jwt/jwt.strategy.ts
  apps/api/src/user/user.service.spec.ts
  apps/api/src/user/user.service.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/s

#176 [Feat] Co-authored-by를 통한 공동 작업자 추가
  .gitmessage
Labels: 🔨 Config, size/xs

#163 [Feat] 참여자 목록 조회 API 구현
  apps/api/src/dashboard/dashboard.controller.ts
  apps/api/src/dashboard/dashboard.service.ts
Labels: BE, ✨ Feature, size/s

#167 [Feat] Header Component 구현
  apps/web/src/assets/ticle.svg
  apps/web/src/components/Header/index.tsx
  apps/web/src/components/common/Header.tsx
  apps/web/src/routes/__root.tsx
  apps/web/tailwind.config.ts
Labels: FE, ✨ Feature, size/s

#170 [Feat] Select 공통 컴포넌트 구현
  apps/web/src/assets/icons/chevron-down.svg
  apps/web/src/assets/icons/chevron-up.svg
  apps/web/src/components/common/Select/index.tsx
  apps/web/tailwind.config.ts
Labels: FE, ✨ Feature, size/m

#169 [Feat] mediaserver 기초세팅
  apps/media/.eslintrc.js
  apps/media/.gitignore
  apps/media/.prettierrc
  apps/media/README.md
  apps/media/nest-cli.json
  apps/media/package.json
  apps/media/src/app.controller.spec.ts
  apps/media/src/app.controller.ts
  apps/media/src/app.module.ts
  apps/media/src/app.service.ts
  apps/media/src/main.ts
  apps/media/test/app.e2e-spec.ts
  apps/media/test/jest-e2e.json
  apps/media/tsconfig.build.json
  apps/media/tsconfig.json
  apps/media/turbo.json
  package.json
  pnpm-lock.yaml
Labels: BE, 🔨 Config, size/l

#172 [Feat] mediasoup 워커 생성 로직 구현
  apps/media/package.json
  apps/media/src/app.module.ts
  apps/media/src/mediasoup/mediasoup.module.ts
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/media/src/signaling/signaling.module.ts
  apps/media/src/signaling/signaling.service.ts
  apps/web/package.json
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/l

#177 [Feat] 방생성 기능 및 이벤트
  apps/media/src/app.module.ts
  apps/media/src/config.ts
  apps/media/src/mediasoup/mediasoup.module.ts
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/peer.ts
  apps/media/src/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/media/src/signaling/signaling.module.ts
Labels: BE, ✨ Feature, size/xl

#178 [Feat] 방 참여 로직 구현 및 이벤트 생성
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/peer.ts
  apps/media/src/room.ts
  apps/media/src/signaling/signaling.gateway.ts
Labels: BE, ✨ Feature, size/s

#179 [Feat] transport 생성 로직 및 생성 요청 event 구현
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/signaling/signaling.gateway.ts
Labels: BE, ✨ Feature, size/xl

#183 [Feat] mediasoup 초기 연결 및 Device 생성
  apps/web/package.json
  apps/web/src/constants/env.ts
  apps/web/src/hooks/useMediasoup.ts
  apps/web/src/hooks/useSocket.ts
  apps/web/src/hooks/useStream.ts
  apps/web/src/types/mediasoup.ts
  apps/web/tsconfig.json
  pnpm-lock.yaml
Labels: FE, ✨ Feature, size/m

#185 [Docs] README 수정
  README.md
Labels: 📝 Docs, size/s

#180 [Feat] Dashboard API 엔드포인트 수정
  apps/api/src/dashboard/dashboard.controller.ts
Labels: BE, ✨ Feature, size/s

#181 [Feat] github Oauth 기능 추가, UserEntity 속성 변경
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.spec.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/dto/localSignupRequest.dto.ts
  apps/api/src/auth/dto/loginResponse.dto.ts
  apps/api/src/auth/github/github-auth.guard.ts
  apps/api/src/auth/github/github.strategy.ts
  apps/api/src/auth/jwt/jwt.strategy.ts
  apps/api/src/entity/user.entity.ts
  apps/api/src/user/dto/createLocalUser.dto.ts
  apps/api/src/user/dto/createSocialUser.dto.ts
  apps/api/src/user/user.service.spec.ts
  apps/api/src/user/user.service.ts
Labels: BE, ✨ Feature, size/m

#192 feat: GetUser decorator 생성
  apps/api/src/common/decorator/get-userId.decorator.ts
Labels: BE, ✨ Feature, size/s

#194 [Feat] Google-Oauth 구현
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/google/google-auth.guard.ts
  apps/api/src/auth/google/google.strategy.ts
Labels: BE, ✨ Feature, size/s

#197 [Feat] mediasoup 이벤트 이름 및 타입 정의
  apps/api/package.json
  apps/web/package.json
  packages/mediasoup/.eslintrc.js
  packages/mediasoup/package.json
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/events.ts
  packages/mediasoup/src/index.ts
  packages/mediasoup/src/server/index.ts
  packages/mediasoup/tsconfig.json
  packages/mediasoup/tsup.config.ts
  packages/shared/index.ts
  packages/shared/package.json
  packages/shared/tsconfig.json
  pnpm-lock.yaml
Labels: 🔨 Config, size/l

#195 [Feat] api 응답 interceptor 구현
  apps/api/src/main.ts
  apps/api/src/response.interceptor.ts
  apps/api/src/response.interface.ts
Labels: BE, ✨ Feature, size/s

#186 [Feat] 티클 개설 페이지 UI 및 validation 구현
  .github/workflows/check.yml
  apps/web/.eslintrc.cjs
  apps/web/package.json
  apps/web/src/assets/icons/close-circle.svg
  apps/web/src/components/common/BasicLayout/index.tsx
  apps/web/src/components/common/SearchInput/index.tsx
  apps/web/src/components/common/TextArea/index.tsx
  apps/web/src/components/common/TextInput/index.tsx
  apps/web/src/components/ticle/open/DateTimePicker.tsx
  apps/web/src/components/ticle/open/FormBox.tsx
  apps/web/src/components/ticle/open/HashtagInput.tsx
  apps/web/src/components/ticle/open/index.tsx
  apps/web/src/routes/__root.tsx
  apps/web/src/routes/dashboard/_layout.tsx
  apps/web/src/routes/ticle/$ticleId.tsx
  apps/web/src/routes/ticle/open.tsx
  apps/web/tsconfig.app.json
  apps/web/tsconfig.node.json
  packages/types/.eslintrc.js
  packages/types/package.json
  packages/types/src/formSchema.ts
  packages/types/src/index.ts
  packages/types/tsconfig.json
  packages/types/tsup.config.ts
  pnpm-lock.yaml
Labels: FE, ✨ Feature, 🎨 Design, size/l

#190 [Feat] API Mocking을 위한 MSW 적용
  apps/web/.eslintrc.cjs
  apps/web/package.json
  apps/web/public/mockServiceWorker.js
  apps/web/src/__mocks__/browsers.ts
  apps/web/src/__mocks__/data/dashboards/applicants-user.json
  apps/web/src/__mocks__/data/dashboards/dashboard.json
  apps/web/src/__mocks__/data/ticles/ticle-detail.json
  apps/web/src/__mocks__/data/ticles/ticle-list.json
  apps/web/src/__mocks__/data/users/signup.json
  apps/web/src/__mocks__/handlers/auth.ts
  apps/web/src/__mocks__/handlers/dashboard.ts
  apps/web/src/__mocks__/handlers/index.ts
  apps/web/src/__mocks__/handlers/ticle.ts
  apps/web/src/constants/env.ts
  apps/web/src/main.tsx
  apps/web/tsconfig.json
  pnpm-lock.yaml
Labels: FE, ✨ Feature, size/l

#187 [Feat] 티클 상세 조회 페이지 퍼블리싱
  apps/web/src/assets/icons/calendar.svg
  apps/web/src/assets/icons/clock.svg
  apps/web/src/components/common/TextArea/index.tsx
  apps/web/src/components/common/TextInput/index.tsx
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/routes/ticle/$ticleId.tsx
  apps/web/src/utils/a11y.ts
  apps/web/src/utils/cn.ts
  apps/web/src/utils/date.ts
  apps/web/tailwind.config.ts
Labels: FE, ✨ Feature, 🎨 Design, size/m

#193 [Feat] Storybook 세팅, 공통 컴포넌트 Story 생성, 배포 CD workflow 설정
  .github/workflows/chromatic.yml
  .github/workflows/labeler.yml
  apps/media/src/app.controller.spec.ts
  apps/media/src/app.controller.ts
  apps/media/src/main.ts
  apps/media/src/mediasoup/mediasoup.module.ts
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/media/src/signaling/signaling.module.ts
  apps/media/test/app.e2e-spec.ts
  apps/web/.gitignore
  apps/web/.storybook/main.ts
  apps/web/.storybook/preview.ts
  apps/web/package.json
  apps/web/src/assets/icons/chevron-down.svg
  apps/web/src/components/common/Avatar/index.tsx
  apps/web/src/hooks/useMediasoup.ts
  apps/web/src/hooks/useStream.ts
  apps/web/src/stories/Avatar.stories.tsx
  apps/web/src/stories/Badge.stories.tsx
  apps/web/src/stories/Button.stories.tsx
  apps/web/src/stories/Dialog.stories.tsx
  apps/web/src/stories/SearchInput.stories.tsx
  apps/web/src/stories/Select.stories.tsx
  apps/web/src/stories/TextArea.stories.tsx
  apps/web/src/stories/TextInput.stories.tsx
  pnpm-lock.yaml
Labels: FE, ✨ Feature, 🎨 Design, size/xl

#199 [Feat] ticle 상세정보에 프로필 이미지 Url 추가
  apps/api/src/ticle/dto/ticleDetailDto.ts
  apps/api/src/ticle/ticle.service.ts
Labels: BE, ✨ Feature, size/s

#201 [Feat] Connect Transport 구현
  apps/media/package.json
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/peer.ts
  apps/media/src/signaling/signaling.gateway.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/m

#212 [Feat] run lint 적용
  README.md
  apps/api/package.json
  apps/media/.prettierrc
  apps/media/src/app.module.ts
  apps/media/src/mediasoup/mediasoup.module.ts
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/peer.ts
  apps/media/src/room/room.module.ts
  apps/media/src/room/room.service.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/media/test/app.e2e-spec.ts
  apps/web/package.json
  packages/mediasoup/.eslintrc.cjs
  packages/mediasoup/package.json
  packages/types/.eslintrc.cjs
  packages/types/package.json
Labels: size/m

#215 [Fix] 프론트 백 연결테스트 및 버그수정
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useRoom.ts
  apps/web/src/hooks/mediasoup/useTransport.ts
  packages/mediasoup/src/client/index.ts
Labels: 🛠️ Fix, BE, size/m

#219 [Feat] socket disconnect 시 close 구현
  apps/media/src/app.controller.spec.ts
  apps/media/src/app.controller.ts
  apps/media/src/app.service.ts
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/peer.ts
  apps/media/src/room/room.service.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
Labels: size/s

#218 [Feat] Mediasoup 비즈니스로직 별 분리
  apps/web/src/assets/icons/camera-off.svg
  apps/web/src/assets/icons/camera-on.svg
  apps/web/src/assets/icons/exit.svg
  apps/web/src/assets/icons/mic-off.svg
  apps/web/src/assets/icons/mic-on.svg
  apps/web/src/assets/icons/screen-off.svg
  apps/web/src/assets/icons/screen-on.svg
  apps/web/src/components/live/index.tsx
  apps/web/src/hooks/mediasoup/useConsumerStream.ts
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useProducerStream.ts
  packages/mediasoup/src/client/index.ts
Labels: FE, size/l

#198 [Feat] 로그인 성공 시 '/' 로 리다이렉션
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.service.spec.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/dto/loginResponse.dto.ts
  apps/api/src/auth/github/github.strategy.ts
  apps/api/src/auth/google/google.strategy.ts
  apps/api/src/auth/local/local.strategy.spec.ts
  apps/api/src/auth/local/local.strategy.ts
  apps/api/src/user/user.service.spec.ts
  apps/api/src/user/user.service.ts
Labels: BE, ✨ Feature, size/m

#223 [Feat] 특정 스트림 종료시 다른 참가자들에게 반영하는 로직 추가
  apps/media/src/mediasoup/mediasoup.module.ts
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/media/src/signaling/signaling.module.ts
  apps/media/tsconfig.json
  apps/web/package.json
  apps/web/src/components/live/index.tsx
  apps/web/src/hooks/mediasoup/useConsumerStream.ts
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useProducerStream.ts
  apps/web/src/hooks/mediasoup/useRoom.ts
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/events.ts
  packages/mediasoup/tsup.config.ts
Labels: FE, BE, ✨ Feature, size/m

#224 [Feat] mediasoup 화면공유 판단 타입 추가
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/room.service.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/index.ts
  packages/mediasoup/src/mediaTypes.ts
  packages/mediasoup/src/server/index.ts
Labels: BE, ✨ Feature, size/s

#222 [Fix] 토큰으로 userId 가져오도록 수정
  apps/api/src/ticle/ticle.controller.ts
Labels: 🛠️ Fix, BE, size/s

#221 [Fix] token 으로 user 가져오기, zod validation 추가
  apps/api/package.json
  apps/api/src/httpexception.filter.ts
  apps/api/src/ticle/dto/createTicleDto.ts
  apps/api/src/ticle/ticle.controller.ts
  apps/api/src/ticle/ticle.service.ts
  apps/api/src/zodpipevalidation.ts
  pnpm-lock.yaml
Labels: 🛠️ Fix, BE, size/s

#226 [Feat] pause & resume 기능 구현
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/signaling/signaling.gateway.ts
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/events.ts
  packages/mediasoup/src/index.ts
  packages/mediasoup/src/mediaTypes.ts
  packages/mediasoup/src/server/index.ts
  packages/mediasoup/src/types.ts
Labels: BE, ✨ Feature, size/m

#229 [Feat] Dashboard에 Dto 생성
  apps/api/src/dashboard/dashboard.controller.ts
  apps/api/src/dashboard/dashboard.service.ts
  apps/api/src/dashboard/dto/getDashboardListQueryDto.ts
  apps/api/src/entity/ticle.entity.ts
  apps/api/src/httpexception.filter.ts
  apps/api/src/ticle/dto/createTicleDto.ts
  apps/api/src/ticle/ticle.controller.ts
  apps/api/src/ticle/ticle.service.ts
  apps/api/src/zodValidationPipe.ts
  apps/media/src/signaling/signaling.gateway.ts
  packages/mediasoup/src/events.ts
  packages/types/src/dashboard/getDashboardList.ts
  packages/types/src/dashboard/index.ts
  packages/types/src/index.ts
  packages/types/src/ticle/index.ts
  packages/types/src/ticle/ticleStatus.ts
  packages/types/tsup.config.ts
Labels: BE, ✨ Feature, size/m

#232 feat: 회원가입 로직에 intercepter 추가
  apps/api/src/app.controller.spec.ts
  apps/api/src/app.controller.ts
  apps/api/src/app.module.ts
  apps/api/src/app.service.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/dto/signupResponse.dto.ts
  apps/media/src/mediasoup/mediasoup.service.ts
Labels: BE, ✨ Feature, size/m

#234 [Feat] 대시보드 신청한 티클 관리 퍼블리싱
  .github/workflows/chromatic.yml
  apps/web/src/components/common/BasicLayout/index.tsx
  apps/web/src/components/common/Select/index.tsx
  apps/web/src/components/common/Tab/index.tsx
  apps/web/src/components/dashboard/DashboardTab.tsx
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/dashboard/apply/index.tsx
  apps/web/src/components/dashboard/index.tsx
  apps/web/src/routes/__root.tsx
  apps/web/src/routes/dashboard/_layout.tsx
  apps/web/src/routes/dashboard/apply.tsx
  apps/web/src/stories/Tab.stories.tsx
Labels: FE, 🎨 Design, size/m

#243 [Fix] .env 저장 경로 변경 및 배포 명령 수정
  apps/api/Dockerfile
  apps/media/Dockerfile
  apps/web/Dockerfile
Labels: 🔨 Config, size/xs

#245 [Docs] readme 수정
  README.md
  apps/web/src/components/live/index.tsx
Labels: 📝 Docs, size/s

#248 [Feat] cookieparser 설치 및 적용
  apps/api/package.json
  apps/api/src/main.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/s

#250 [Feat] 로그인 정보 없을떄 에러추가, 토큰인증실패시 에러추가
  apps/api/src/auth/jwt/jwt-auth.guard.ts
Labels: BE, ✨ Feature, size/s

#256 [Fix] applicant Count 수정
  apps/api/src/ticle/ticle.service.ts
Labels: 🛠️ Fix, BE, size/s

#253 [Feat] 메인 페이지(티클 목록 페이지) 퍼블리싱 및 API 연동
  apps/web/package.json
  apps/web/src/api/ticle.ts
  apps/web/src/assets/icons/calendar.svg
  apps/web/src/assets/icons/person-line.svg
  apps/web/src/assets/images/banner-illustration.png
  apps/web/src/assets/images/ticle-character.png
  apps/web/src/components/common/SearchInput/index.tsx
  apps/web/src/components/common/Select/index.tsx
  apps/web/src/components/ticle/list/Banner.tsx
  apps/web/src/components/ticle/list/TicleCard.tsx
  apps/web/src/components/ticle/list/index.tsx
  apps/web/src/hooks/api/request.ts
  apps/web/src/hooks/api/ticle.ts
  apps/web/src/main.tsx
  apps/web/src/routes/__root.tsx
  apps/web/src/routes/index.tsx
  apps/web/src/styles/global.css
  apps/web/src/utils/date.ts
  packages/types/src/ticle/index.ts
  packages/types/src/ticle/ticleList.ts
  pnpm-lock.yaml
Labels: FE, ✨ Feature, 🎨 Design, size/m

#255 [Feat] database exceptionfilter 적용
  apps/api/package.json
  apps/api/src/auth/auth.service.spec.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/common/filter/db-exception.filter.ts
  apps/api/src/common/filter/http-exception.filter.ts
  apps/api/src/dashboard/dashboard.service.ts
  apps/api/src/main.ts
  apps/api/src/ticle/ticle.service.ts
  apps/api/src/user/user.service.spec.ts
  apps/api/src/user/user.service.ts
  apps/api/test/app.e2e-spec.ts
  apps/api/test/jest-e2e.json
  apps/media/package.json
  apps/media/test/app.e2e-spec.ts
  apps/media/test/jest-e2e.json
Labels: BE, ✨ Feature, size/m

#271 [Feat] new-producer, get-producers 이벤트 응답객체, join-room이벤트 파라미터에 nickname 추가
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/peer.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/server/index.ts
  packages/types/src/ticle/ticleDetail.ts
Labels: BE, ✨ Feature, size/s

#272 [Feat] error message 타입 선언 및 사용
  apps/api/src/auth/jwt/jwt-auth.guard.ts
  apps/api/src/common/decorator/get-userId.decorator.ts
  apps/api/src/ticle/ticle.service.ts
  apps/api/src/user/user.service.ts
  apps/media/package.json
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/peer.ts
  apps/media/src/room/room.service.ts
  apps/media/src/room/room.ts
  packages/types/src/errorMessages.ts
  packages/types/src/index.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/s

#278 [Fix] totalItemCount, isOpen 수정
  apps/api/package.json
  apps/api/src/main.ts
  apps/api/src/ticle/dto/getTicleListQueryDto.ts
  apps/api/src/ticle/ticle.service.ts
  pnpm-lock.yaml
Labels: 🛠️ Fix, BE, size/m

#279 [Feat] 무한 스크롤, 로딩 인디케이터, 엠티 뷰, 오류 alert
  apps/web/src/components/common/Empty/index.tsx
  apps/web/src/components/common/Header/index.tsx
  apps/web/src/components/common/Loading/Loading.tsx
  apps/web/src/components/common/Loading/index.tsx
  apps/web/src/components/common/Tab/index.tsx
  apps/web/src/components/dashboard/DashboardTab.tsx
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/dashboard/apply/index.tsx
  apps/web/src/components/dashboard/open/ApplicantsDialog.tsx
  apps/web/src/components/dashboard/open/TicleInfoCard.tsx
  apps/web/src/components/dashboard/open/index.tsx
  apps/web/src/components/live/VideoPlayer.tsx
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/components/ticle/list/TicleCard.tsx
  apps/web/src/components/ticle/list/index.tsx
  apps/web/src/hooks/api/dashboard.ts
  apps/web/src/hooks/api/ticle.ts
  apps/web/src/hooks/useIntersectionObserver.ts
  apps/web/src/routes/__root.tsx
  apps/web/src/routes/dashboard/_layout.tsx
  apps/web/src/routes/index.tsx
  apps/web/src/routes/ticle/$ticleId.tsx
  apps/web/src/routes/ticle/open.tsx
  apps/web/src/stories/Loading.stories.tsx
  apps/web/src/stories/Tab.stories.tsx
  apps/web/src/styles/global.css
  apps/web/src/utils/errorHandler.ts
  apps/web/src/utils/queryClient.ts
  apps/web/tailwind.config.ts
Labels: FE, ✨ Feature, 🎨 Design, size/l

#275 [Feat] guest login 도입
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/ticle/ticle.controller.ts
  apps/api/src/user/user.service.spec.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/s

#273 [Refactor] Context API를 통한 mediasoup 관련 로직 분리
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/peer.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/web/.eslintrc.cjs
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/components/live/StreamView/AudioPlayer.tsx
  apps/web/src/components/live/StreamView/PaginationControls.tsx
  apps/web/src/components/live/StreamView/SubVideoGrid.tsx
  apps/web/src/components/live/StreamView/VideoGrid.tsx
  apps/web/src/components/live/StreamView/VideoPlayer.tsx
  apps/web/src/components/live/StreamView/index.tsx
  apps/web/src/components/live/index.tsx
  apps/web/src/contexts/localStream/context.ts
  apps/web/src/contexts/localStream/provider.tsx
  apps/web/src/contexts/mediasoup/context.ts
  apps/web/src/contexts/mediasoup/provider.tsx
  apps/web/src/contexts/remoteStream/context.ts
  apps/web/src/contexts/remoteStream/provider.tsx
  apps/web/src/hooks/mediasoup/useConsumerStream.ts
  apps/web/src/hooks/mediasoup/useLocalStream.ts
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useProducer.ts
  apps/web/src/hooks/mediasoup/useProducerStream.ts
  apps/web/src/hooks/mediasoup/useRemoteStream.ts
  apps/web/src/hooks/mediasoup/useRoom.ts
  apps/web/src/hooks/mediasoup/useSocket.ts
  apps/web/src/hooks/mediasoup/useTransport.ts
  apps/web/src/routes/live/$ticleId.tsx
  apps/web/src/utils/stream.ts
  packages/mediasoup/src/events.ts
Labels: FE, ♻️ Refactor, size/xl

#284 [Refactor] 비디오 Grid UI 변경
  apps/web/src/components/common/Avatar/index.tsx
  apps/web/src/components/live/StreamView/PaginationControls.tsx
  apps/web/src/components/live/StreamView/SubVideoGrid.tsx
  apps/web/src/components/live/StreamView/VideoGrid.tsx
  apps/web/src/components/live/StreamView/VideoPlayer.tsx
  apps/web/src/components/live/StreamView/index.tsx
  apps/web/src/components/live/index.tsx
Labels: FE, 🎨 Design, ♻️ Refactor, size/m

#282 [Feat] 티클 조회 & 목록 조회시 필드 추가
  apps/api/src/ticle/dto/ticleDetailDto.ts
  apps/api/src/ticle/ticle.controller.ts
  apps/api/src/ticle/ticle.service.ts
Labels: BE, ✨ Feature, size/s

#294 [Feat] 프로필 정보 UI 구현
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/github/github.strategy.ts
  apps/api/src/auth/google/google.strategy.ts
  apps/api/src/entity/ticle.entity.ts
  apps/api/src/entity/user.entity.ts
  apps/api/src/ticle/ticle.service.ts
  apps/api/src/user/dto/createLocalUser.dto.ts
  apps/api/src/user/dto/createSocialUser.dto.ts
  apps/api/src/user/dto/userProfileDto.ts
  apps/api/src/user/dto/userProfileOfMeDto.ts
  apps/api/src/user/user.service.ts
  apps/web/.eslintrc.cjs
  apps/web/src/__mocks__/handlers/auth.ts
  apps/web/src/api/auth.ts
  apps/web/src/api/user.ts
  apps/web/src/components/auth/GuestLogin.tsx
  apps/web/src/components/common/Avatar/index.tsx
  apps/web/src/components/common/Header/User.tsx
  apps/web/src/components/common/Header/index.tsx
  apps/web/src/components/live/StreamView/AudioPlayer.tsx
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/components/ticle/list/TicleCard.tsx
  apps/web/src/components/ticle/list/index.tsx
  apps/web/src/components/user/UserInfo.tsx
  apps/web/src/components/user/UserProfileDialog.tsx
  apps/web/src/components/user/UserProfileOfMeDialog.tsx
  apps/web/src/hooks/api/auth.ts
  apps/web/src/hooks/api/user.ts
  apps/web/src/stories/Avatar.stories.tsx
  apps/web/src/stories/Select.stories.tsx
  packages/types/src/index.ts
  packages/types/src/ticle/ticleDetail.ts
  packages/types/src/ticle/ticleList.ts
  packages/types/src/user/index.ts
  packages/types/src/user/provider.ts
  packages/types/src/user/userProfile.ts
  packages/types/src/user/userProfileOfMe.ts
Labels: FE, ✨ Feature, 🎨 Design, size/m

#296 [Feat] SVG 변경에 따른 기본 style 수정
  apps/api/src/main.ts
  apps/web/src/components/live/StreamView/List/PaginationControls.tsx
Labels: FE, ✨ Feature, size/s

#299 [Fix] storybook searchinput type error
  apps/web/src/stories/SearchInput.stories.tsx
Labels: size/xs

#316 [Feat] 티클 삭제 api 구현하기
  apps/api/src/entity/applicant.entity.ts
  apps/api/src/entity/summary.entity.ts
  apps/api/src/ticle/ticle.controller.ts
  apps/api/src/ticle/ticle.service.ts
  packages/types/src/errorMessages.ts
Labels: BE, ✨ Feature, size/s

#312 [Feat] 티클 상세 조회시 isOwner, alreadyApplied에 따른 신청 버튼 분기처리
  apps/api/src/ticle/ticle.service.ts
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/hooks/api/ticle.ts
  packages/types/src/ticle/ticleDetail.ts
Labels: size/s

#308 [Feat] media 서버 이벤트 정리 및 Consumer 상태 관리 이벤트 추가
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/peer.ts
  apps/media/src/signaling/signaling.gateway.ts
  packages/mediasoup/src/events.ts
Labels: BE, ✨ Feature, size/m

#309 [Feat] 자잘한 UI 개선사항 반영
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/dashboard/open/TicleInfoCard.tsx
  apps/web/src/components/ticle/list/TicleCard.tsx
  apps/web/src/components/user/UserProfileDialog.tsx
  apps/web/src/styles/global.css
Labels: size/s

#311 [Feat] 인증 정보를 전역 상태로 관리, 로그인 필요한 페이지에 접속시 로그인 페이지로 리다이렉트
  apps/web/package.json
  apps/web/src/components/common/Header/User.tsx
  apps/web/src/components/common/Header/index.tsx
  apps/web/src/components/dashboard/DashboardTab.tsx
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/hooks/mediasoup/useProducer.ts
  apps/web/src/hooks/mediasoup/useRemoteStream.ts
  apps/web/src/hooks/mediasoup/useRoom.ts
  apps/web/src/hooks/mediasoup/useTransport.ts
  apps/web/src/hooks/useAuthInfo.ts
  apps/web/src/routeTree.gen.ts
  apps/web/src/routes/_authenticated/_layout.tsx
  apps/web/src/routes/_authenticated/dashboard/_layout.tsx
  apps/web/src/routes/_authenticated/dashboard/apply.tsx
  apps/web/src/routes/_authenticated/dashboard/open.tsx
  apps/web/src/routes/_authenticated/live/$ticleId.tsx
  apps/web/src/routes/_authenticated/ticle/$ticleId.tsx
  apps/web/src/routes/_authenticated/ticle/open.tsx
  apps/web/src/stores/useAuthStore.ts
  pnpm-lock.yaml
Labels: size/m

#313 [Feat] Select 공통 컴포넌트 개선
  apps/web/src/components/common/Select/index.tsx
Labels: size/s

#323 [Feat] 티클 삭제 구현
  apps/api/src/ticle/ticle.controller.ts
  apps/web/src/api/ticle.ts
  apps/web/src/assets/icons/trash.svg
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/hooks/api/ticle.ts
Labels: FE, ✨ Feature, size/s

#324 [Refactor] 현재 그리드에 존재하는 비디오에 대한 스트림 정보를 받아오도록 변경
  apps/media/package.json
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/peer.ts
  apps/media/src/room/room.service.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/web/src/components/live/StreamView/List/Pinned.tsx
  apps/web/src/components/live/StreamView/List/SubVideoGrid.tsx
  apps/web/src/components/live/StreamView/List/VideoGrid.tsx
  apps/web/src/components/live/StreamView/List/VideoPlayer.tsx
  apps/web/src/components/live/StreamView/index.tsx
  apps/web/src/contexts/remoteStream/context.ts
  apps/web/src/contexts/remoteStream/provider.tsx
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useProducer.ts
  apps/web/src/hooks/mediasoup/useRemoteStream.ts
  apps/web/src/hooks/useDebounce.ts
  apps/web/src/hooks/usePagination.ts
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/events.ts
  packages/mediasoup/src/server/index.ts
  packages/types/src/user/userProfile.ts
  packages/types/src/user/userProfileOfMe.ts
  pnpm-lock.yaml
Labels: FE, BE, ♻️ Refactor, size/l

#326 [Fix] AudioPlayer Props 에서 nickname 제거
  apps/web/src/components/live/StreamView/AudioStreams/AudioPlayer.tsx
Labels: 🛠️ Fix, FE, size/xs

#328 [Docs] README 수정
  README.md
Labels: 📝 Docs, size/s

#320 [Feat] Ticle Status 세분화
  apps/api/src/dashboard/dashboard.controller.ts
  apps/api/src/dashboard/dashboard.service.ts
  apps/api/src/ticle/ticle.service.ts
  packages/types/src/dashboard/getDashboardList.ts
  packages/types/src/errorMessages.ts
  packages/types/src/ticle/ticleDetail.ts
  packages/types/src/ticle/ticleStatus.ts
Labels: BE, ✨ Feature, size/m
