Repository boostcampwm-2024/web21-TICLE, pull requests merged in 2024-12, with the labels that each got.

#336 [Docs] README 업데이트
  README.md
Labels: 📝 Docs, size/m

#292 [Feat] object storage 파일 업로드 기능 구현
  apps/media/package.json
  apps/media/src/ncp/ncp.config.ts
  apps/media/src/ncp/ncp.module.ts
  apps/media/src/ncp/ncp.service.ts
  packages/types/src/errorMessages.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/xl

#302 [Feat] 오디오 텍스트로 변환 및 요약 로직 구현
  apps/api/src/entity/summary.entity.ts
  apps/api/src/stream/dto/createSummaryDto.ts
  apps/api/src/stream/stream.controller.ts
  apps/api/src/stream/stream.module.ts
  apps/api/src/stream/stream.service.ts
  packages/types/src/errorMessages.ts
Labels: BE, ✨ Feature, size/m

#329 [Feat] 티클 상태에 따른 조건부 처리, 티클 시작/종료 API 연결
  apps/api/src/ticle/dto/ticleDetailDto.ts
  apps/api/src/ticle/ticle.service.ts
  apps/web/src/api/dashboard.ts
  apps/web/src/api/live.ts
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/dashboard/open/TicleInfoCard.tsx
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/components/live/index.tsx
  apps/web/src/components/ticle/detail/CtaButton.tsx
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/hooks/api/dashboard.ts
  apps/web/src/hooks/api/live.ts
Labels: FE, ✨ Feature, 🎨 Design, size/m

#334 [Feat] Peer 접속시 UI 상에 Dummy User 반영
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/components/live/StreamView/List/SubVideoGrid.tsx
  apps/web/src/components/live/StreamView/List/VideoGrid.tsx
  apps/web/src/components/live/StreamView/List/VideoPlayer.tsx
  apps/web/src/components/live/StreamView/index.tsx
  apps/web/src/contexts/dummyStream/context.ts
  apps/web/src/contexts/dummyStream/provider.tsx
  apps/web/src/contexts/localStream/context.ts
  apps/web/src/contexts/localStream/provider.tsx
  apps/web/src/contexts/mediasoup/provider.tsx
  apps/web/src/contexts/remoteStream/context.ts
  apps/web/src/contexts/remoteStream/provider.tsx
  apps/web/src/hooks/mediasoup/useLocalStream.ts
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useRemoteStream.ts
  apps/web/src/hooks/mediasoup/useSocket.ts
  apps/web/src/hooks/usePagination.ts
  apps/web/src/routes/_authenticated/live/$ticleId.tsx
Labels: FE, ✨ Feature, size/m

#340 [Feat] 티클 상세조회 guard 제거, query param 생성
  apps/api/src/ticle/ticle.controller.ts
Labels: BE, ✨ Feature, size/xs

#333 [Feat] logger 적용
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/common/Interceptor/response.interceptor.ts
  apps/api/src/common/Interceptor/response.interface.ts
  apps/api/src/common/filter/http-exception.filter.ts
  apps/api/src/common/log/logger.batch.ts
  apps/api/src/common/log/logger.middleware.ts
  apps/api/src/common/log/logger.module.ts
  apps/api/src/common/log/logger.service.ts
  apps/api/src/common/ncp/ncp.module.ts
  apps/api/src/common/ncp/ncp.service.ts
  apps/api/src/common/pipe/zodValidationPipe.ts
  apps/api/src/config/ncp.config.ts
  apps/api/src/config/winston.confing.ts
  apps/api/src/dashboard/dashboard.controller.ts
  apps/api/src/main.ts
  apps/api/src/ticle/ticle.controller.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/l

#346 [Fix] 티클 서비스 쿼리 수정
  apps/api/src/ticle/ticle.service.ts
Labels: 🛠️ Fix, BE, size/xs

#350 [feat] 회의실 전체 종료 로직 구현
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/room/room.service.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/media/src/signaling/signaling.service.ts
Labels: BE, ✨ Feature, size/s

#351 [Fix] log 없을시 에러처리 추가
  apps/api/src/common/log/logger.batch.ts
  apps/api/src/common/ncp/ncp.service.ts
  apps/api/src/config/winston.confing.ts
Labels: size/s

#349 [Feat] Observer Pattern을 통한 Toast Message 추가
  apps/web/.eslintrc.cjs
  apps/web/src/components/toast/Toast.tsx
  apps/web/src/components/toast/ToastContainer.tsx
  apps/web/src/components/toast/ToastTransition.tsx
  apps/web/src/constants/toast.ts
  apps/web/src/core/toast/eventManager.ts
  apps/web/src/core/toast/index.ts
  apps/web/src/core/toast/type.ts
  apps/web/src/core/toast/utils.ts
  apps/web/src/hooks/toast/useToast.ts
  apps/web/src/hooks/toast/useToastContainer.ts
  apps/web/src/routes/__root.tsx
  apps/web/src/utils/toast/collapseToast.ts
  apps/web/src/utils/toast/typeGuard.ts
  apps/web/tailwind.config.ts
Labels: FE, ✨ Feature, size/m

#353 [Feat] 음성녹음 및 ai 파이프라인 연결
  apps/api/src/entity/summary.entity.ts
  apps/media/package.json
  apps/media/src/mediasoup/config.ts
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/ncp/ncp.module.ts
  apps/media/src/ncp/ncp.service.ts
  apps/media/src/record/record.module.ts
  apps/media/src/record/record.service.ts
  apps/media/src/record/recordInfo.ts
  apps/media/src/room/peer.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/media/src/signaling/signaling.module.ts
  apps/web/src/components/live/SettingDialog/AiSummary.tsx
  apps/web/src/components/live/SettingDialog/SelectMedia.tsx
  apps/web/src/components/live/SettingDialog/index.tsx
  packages/mediasoup/src/events.ts
  packages/types/src/errorMessages.ts
  pnpm-lock.yaml
Labels: BE, ✨ Feature, size/l

#359 [Fix] 초기 유저 접속시 로딩 섹션이 깜빡이는 현상 수정
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/components/live/StreamView/List/Pinned.tsx
  apps/web/src/components/live/StreamView/List/SubVideoGrid.tsx
  apps/web/src/components/live/StreamView/List/UnPinned.tsx
  apps/web/src/components/live/StreamView/List/VideoGrid.tsx
  apps/web/src/components/live/StreamView/index.tsx
  apps/web/src/contexts/dummyStream/context.ts
  apps/web/src/contexts/dummyStream/provider.tsx
  apps/web/src/contexts/localStream/context.ts
  apps/web/src/contexts/localStream/provider.tsx
  apps/web/src/contexts/mediasoup/context.ts
  apps/web/src/contexts/mediasoup/provider.tsx
  apps/web/src/contexts/remoteStream/context.ts
  apps/web/src/contexts/remoteStream/provider.tsx
  apps/web/src/hooks/mediasoup/useLocalStream.ts
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useRemoteStream.ts
  apps/web/src/hooks/useAudioState.ts
  apps/web/src/hooks/useMediaTracks.ts
  apps/web/src/hooks/usePagination.ts
  apps/web/src/hooks/usePinnedVideo.ts
  apps/web/src/routes/_authenticated/live/$ticleId.tsx
  packages/mediasoup/src/client/index.ts
Labels: FE, 🐞 Bug, size/m

#363 [Docs] 운영진 피드백 반영하여 README 수정
  README.md
Labels: 📝 Docs, size/s

#360 [Feat] 티클 참여 및 종료 관련 세부 처리
  apps/web/src/api/ticle.ts
  apps/web/src/components/common/Alert/index.tsx
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/components/live/index.tsx
  apps/web/src/components/ticle/detail/index.tsx
  apps/web/src/components/toast/Toast.tsx
  apps/web/src/hooks/api/live.ts
  apps/web/src/hooks/api/ticle.ts
  apps/web/src/hooks/mediasoup/useSocket.ts
  apps/web/src/routeTree.gen.ts
  apps/web/src/routes/_authenticated/_layout.tsx
  apps/web/src/routes/ticle/$ticleId.tsx
  apps/web/src/stores/useAuthStore.ts
Labels: FE, ✨ Feature, size/m

#361 [Feat] AI 요약 클라이언트 연결
  apps/web/src/api/dashboard.ts
  apps/web/src/assets/icons/ai-summary.svg
  apps/web/src/components/dashboard/AiSummaryDialog.tsx
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/dashboard/open/TicleInfoCard.tsx
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/components/live/SettingDialog/AiSummary.tsx
  apps/web/src/components/live/SettingDialog/index.tsx
  apps/web/src/hooks/api/dashboard.ts
  packages/types/src/dashboard/getDashboardList.ts
Labels: FE, ✨ Feature, 🎨 Design, size/m

#364 [Feat] Inbound 네트워크 품질에 따라 Consumer Layer 설정 추가
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/web/src/components/live/StreamView/List/Pinned.tsx
  apps/web/src/components/live/StreamView/List/UnPinned.tsx
  apps/web/src/hooks/mediasoup/useNetworkMonitor.ts
  apps/web/src/hooks/mediasoup/useRemoteStream.ts
  apps/web/src/hooks/usePagination.ts
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/events.ts
  packages/mediasoup/src/server/index.ts
Labels: FE, ✨ Feature, size/m

#366 [Feat] Media서버 Docker 설정 변경
  .github/workflows/back-media-cd.yml
  apps/media/Dockerfile
Labels: BE, ✨ Feature, size/xs

#370 [Fix] AI 요약이 제대로 응답하지 않던 오류 수정
  apps/api/src/entity/summary.entity.ts
  apps/api/src/stream/stream.controller.ts
  apps/api/src/stream/stream.service.ts
  apps/web/src/components/dashboard/AiSummaryDialog.tsx
  apps/web/src/components/live/SettingDialog/SelectMedia.tsx
  apps/web/src/hooks/useMediaTracks.ts
  apps/web/src/utils/stream.ts
  packages/types/src/dashboard/getDashboardList.ts
Labels: 🛠️ Fix, size/s, 🎉 Release

#371 [Release] 5차 배포
  apps/api/src/entity/summary.entity.ts
  apps/api/src/stream/stream.controller.ts
  apps/api/src/stream/stream.service.ts
  apps/web/src/components/dashboard/AiSummaryDialog.tsx
  apps/web/src/components/live/SettingDialog/SelectMedia.tsx
  apps/web/src/hooks/useMediaTracks.ts
  apps/web/src/utils/stream.ts
  packages/types/src/dashboard/getDashboardList.ts
Labels: size/s, 🎉 Release

#372 [Feat] 발표자가 탭 닫기로 접속 종료 시에도 방폭되게 함
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/record/record.service.ts
  apps/media/src/record/recordInfo.ts
  apps/media/src/room/room.service.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/media/src/signaling/signaling.module.ts
Labels: BE, ✨ Feature, size/s

#376 [Feat] 대시보드 조회시에 summary 여부 판단 추가
  apps/api/src/dashboard/dashboard.module.ts
  apps/api/src/dashboard/dashboard.service.ts
Labels: BE, ✨ Feature, size/s

#378 [Feat] 대시보드 UI 수정, summary 여부에 따른 AI 요약 확인 버튼 분기
  apps/web/src/components/dashboard/AiSummaryDialog.tsx
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/dashboard/apply/index.tsx
  apps/web/src/components/dashboard/open/TicleInfoCard.tsx
  apps/web/src/components/dashboard/open/index.tsx
  packages/types/src/dashboard/getDashboardList.ts
Labels: FE, 🎨 Design, size/s

#382 [Feat] 방장이 X버튼으로 종료시 티클 종료 처리
  apps/web/src/components/live/ControlBar/index.tsx
Labels: FE, ✨ Feature, size/s

#384 [Feat] 티클 종료 status 변경 시점 변경
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/hooks/mediasoup/useMediasoup.ts
Labels: FE, ✨ Feature, size/s

#377 [Feat] 올바르지 않은 경로/환경으로 요청시 오류를 반환하는 컴포넌트 추가
  apps/web/src/components/NotFound.tsx
  apps/web/src/components/NotSupportedMobile.tsx
  apps/web/src/hooks/mediasoup/useSocket.ts
  apps/web/src/routes/__root.tsx
Labels: FE, ✨ Feature, size/s

#386 [Fix] ticle entity 의 colum 형식 수정
  apps/api/src/entity/ticle.entity.ts
Labels: 🛠️ Fix, BE, size/xs

#385 [Release] 6차 배포 (12.06)
  README.md
  apps/api/src/dashboard/dashboard.module.ts
  apps/api/src/dashboard/dashboard.service.ts
  apps/api/src/entity/ticle.entity.ts
  apps/media/src/mediasoup/config.ts
  apps/media/src/mediasoup/mediasoup.service.ts
  apps/media/src/record/record.service.ts
  apps/media/src/record/recordInfo.ts
  apps/media/src/room/room.service.ts
  apps/media/src/room/room.ts
  apps/media/src/signaling/signaling.gateway.ts
  apps/media/src/signaling/signaling.module.ts
  apps/web/src/components/NotFound.tsx
  apps/web/src/components/NotSupportedMobile.tsx
  apps/web/src/components/dashboard/AiSummaryDialog.tsx
  apps/web/src/components/dashboard/apply/TicleInfoCard.tsx
  apps/web/src/components/dashboard/apply/index.tsx
  apps/web/src/components/dashboard/open/ApplicantsDialog.tsx
  apps/web/src/components/dashboard/open/TicleInfoCard.tsx
  apps/web/src/components/dashboard/open/index.tsx
  apps/web/src/components/live/ControlBar/index.tsx
  apps/web/src/hooks/api/dashboard.ts
  apps/web/src/hooks/mediasoup/useMediasoup.ts
  apps/web/src/hooks/mediasoup/useNetworkMonitor.ts
  apps/web/src/hooks/mediasoup/useRemoteStream.ts
  apps/web/src/hooks/mediasoup/useSocket.ts
  apps/web/src/hooks/useMediaTracks.ts
  apps/web/src/routes/__root.tsx
  packages/mediasoup/src/client/index.ts
  packages/mediasoup/src/server/index.ts
  packages/types/src/dashboard/getDashboardList.ts
Labels: size/m, 🎉 Release

#387 [Fix] MediaStream 기본 화질 변경
  apps/media/src/mediasoup/config.ts
  apps/web/src/utils/stream.ts
Labels: 🛠️ Fix, FE, size/s

#388 [Release] 7차 배포 (12.06)
  apps/media/src/mediasoup/config.ts
  apps/web/src/utils/stream.ts
Labels: size/s, 🎉 Release
